//
//  Currency.swift
//  BBServices
//
//  Created by Nitin kachhadiya on 26/09/20.
//  Copyright © 2020 Nitin kachhadiya. All rights reserved.
//

import Foundation

public struct Currency: Hashable, Codable, Identifiable {
    
    public let id = UUID()
    public let code: String
    public let decimals: Int
    public let name: String
    public let number: String
}

typealias Currencies = [Currency]

extension Currency {

    public static let currencies: [Currency] = [
        
        Currency(code:"AED",decimals:2,name:"United Arab Emirates dirham",number:"784"),
        Currency(code:"AFN",decimals:2,name:"Afghan afghani",number:"971"),
        Currency(code:"ALL",decimals:2,name:"Albanian lek",number:"8"),
        Currency(code:"AMD",decimals:2,name:"Armenian dram",number:"51"),
        Currency(code:"ANG",decimals:2,name:"Netherlands Antillean guilder",number:"532"),
        Currency(code:"AOA",decimals:2,name:"Angolan kwanza",number:"973"),
        Currency(code:"ARS",decimals:2,name:"Argentine peso",number:"32"),
        Currency(code:"AUD",decimals:2,name:"Australian dollar",number:"36"),
        Currency(code:"AWG",decimals:2,name:"Aruban florin",number:"533"),
        Currency(code:"AZN",decimals:2,name:"Azerbaijani manat",number:"944"),
        Currency(code:"BAM",decimals:2,name:"Bosnia and Herzegovina convertible mark",number:"977"),
        Currency(code:"BBD",decimals:2,name:"Barbados dollar",number:"52"),
        Currency(code:"BDT",decimals:2,name:"Bangladeshi taka",number:"50"),
        Currency(code:"BGN",decimals:2,name:"Bulgarian lev",number:"975"),
        Currency(code:"BHD",decimals:3,name:"Bahraini dinar",number:"48"),
        Currency(code:"BIF",decimals:0,name:"Burundian franc",number:"108"),
        Currency(code:"BMD",decimals:2,name:"Bermudian dollar (customarily known as Bermuda dollar)",number:"60"),
        Currency(code:"BND",decimals:2,name:"Brunei dollar",number:"96"),
        Currency(code:"BOB",decimals:2,name:"Boliviano",number:"68"),
        Currency(code:"BOV",decimals:2,name:"Bolivian Mvdol (funds code)",number:"984"),
        Currency(code:"BRL",decimals:2,name:"Brazilian real",number:"986"),
        Currency(code:"BSD",decimals:2,name:"Bahamian dollar",number:"44"),
        Currency(code:"BTN",decimals:2,name:"Bhutanese ngultrum",number:"64"),
        Currency(code:"BWP",decimals:2,name:"Botswana pula",number:"72"),
        Currency(code:"BYR",decimals:0,name:"Belarusian ruble",number:"974"),
        Currency(code:"BZD",decimals:2,name:"Belize dollar",number:"84"),
        Currency(code:"CAD",decimals:2,name:"Canadian dollar",number:"124"),
        Currency(code:"CDF",decimals:2,name:"Congolese franc",number:"976"),
        Currency(code:"CHE",decimals:2,name:"WIR Euro (complementary currency)",number:"947"),
        Currency(code:"CHF",decimals:2,name:"Swiss franc",number:"756"),
        Currency(code:"CHW",decimals:2,name:"WIR Franc (complementary currency)",number:"948"),
        Currency(code:"CLF",decimals:0,name:"Unidad de Fomento (funds code)",number:"990"),
        Currency(code:"CLP",decimals:0,name:"Chilean peso",number:"152"),
        Currency(code:"CNY",decimals:2,name:"Chinese yuan",number:"156"),
        Currency(code:"COP",decimals:2,name:"Colombian peso",number:"170"),
        Currency(code:"COU",decimals:2,name:"Unidad de Valor Real",number:"970"),
        Currency(code:"CRC",decimals:2,name:"Costa Rican colon",number:"188"),
        Currency(code:"CUC",decimals:2,name:"Cuban convertible peso",number:"931"),
        Currency(code:"CUP",decimals:2,name:"Cuban peso",number:"192"),
        Currency(code:"CVE",decimals:0,name:"Cape Verde escudo",number:"132"),
        Currency(code:"CZK",decimals:2,name:"Czech koruna",number:"203"),
        Currency(code:"DJF",decimals:0,name:"Djiboutian franc",number:"262"),
        Currency(code:"DKK",decimals:2,name:"Danish krone",number:"208"),
        Currency(code:"DOP",decimals:2,name:"Dominican peso",number:"214"),
        Currency(code:"DZD",decimals:2,name:"Algerian dinar",number:"12"),
        Currency(code:"EGP",decimals:2,name:"Egyptian pound",number:"818"),
        Currency(code:"ERN",decimals:2,name:"Eritrean nakfa",number:"232"),
        Currency(code:"ETB",decimals:2,name:"Ethiopian birr",number:"230"),
        Currency(code:"EUR",decimals:2,name:"Euro",number:"978"),
        Currency(code:"FJD",decimals:2,name:"Fiji dollar",number:"242"),
        Currency(code:"FKP",decimals:2,name:"Falkland Islands pound",number:"238"),
        Currency(code:"GBP",decimals:2,name:"Pound sterling",number:"826"),
        Currency(code:"GEL",decimals:2,name:"Georgian lari",number:"981"),
        Currency(code:"GHS",decimals:2,name:"Ghanaian cedi",number:"936"),
        Currency(code:"GIP",decimals:2,name:"Gibraltar pound",number:"292"),
        Currency(code:"GMD",decimals:2,name:"Gambian dalasi",number:"270"),
        Currency(code:"GNF",decimals:0,name:"Guinean franc",number:"324"),
        Currency(code:"GTQ",decimals:2,name:"Guatemalan quetzal",number:"320"),
        Currency(code:"GYD",decimals:2,name:"Guyanese dollar",number:"328"),
        Currency(code:"HKD",decimals:2,name:"Hong Kong dollar",number:"344"),
        Currency(code:"HNL",decimals:2,name:"Honduran lempira",number:"340"),
        Currency(code:"HRK",decimals:2,name:"Croatian kuna",number:"191"),
        Currency(code:"HTG",decimals:2,name:"Haitian gourde",number:"332"),
        Currency(code:"HUF",decimals:2,name:"Hungarian forint",number:"348"),
        Currency(code:"IDR",decimals:2,name:"Indonesian rupiah",number:"360"),
        Currency(code:"ILS",decimals:2,name:"Israeli new shekel",number:"376"),
        Currency(code:"INR",decimals:2,name:"Indian rupee",number:"356"),
        Currency(code:"IQD",decimals:3,name:"Iraqi dinar",number:"368"),
        Currency(code:"IRR",decimals:0,name:"Iranian rial",number:"364"),
        Currency(code:"ISK",decimals:0,name:"Icelandic króna",number:"352"),
        Currency(code:"JMD",decimals:2,name:"Jamaican dollar",number:"388"),
        Currency(code:"JOD",decimals:3,name:"Jordanian dinar",number:"400"),
        Currency(code:"JPY",decimals:0,name:"Japanese yen",number:"392"),
        Currency(code:"KES",decimals:2,name:"Kenyan shilling",number:"404"),
        Currency(code:"KGS",decimals:2,name:"Kyrgyzstani som",number:"417"),
        Currency(code:"KHR",decimals:2,name:"Cambodian riel",number:"116"),
        Currency(code:"KMF",decimals:0,name:"Comoro franc",number:"174"),
        Currency(code:"KPW",decimals:0,name:"North Korean won",number:"408"),
        Currency(code:"KRW",decimals:0,name:"South Korean won",number:"410"),
        Currency(code:"KWD",decimals:3,name:"Kuwaiti dinar",number:"414"),
        Currency(code:"KYD",decimals:2,name:"Cayman Islands dollar",number:"136"),
        Currency(code:"KZT",decimals:2,name:"Kazakhstani tenge",number:"398"),
        Currency(code:"LAK",decimals:0,name:"Lao kip",number:"418"),
        Currency(code:"LBP",decimals:0,name:"Lebanese pound",number:"422"),
        Currency(code:"LKR",decimals:2,name:"Sri Lankan rupee",number:"144"),
        Currency(code:"LRD",decimals:2,name:"Liberian dollar",number:"430"),
        Currency(code:"LSL",decimals:2,name:"Lesotho loti",number:"426"),
        Currency(code:"LTL",decimals:2,name:"Lithuanian litas",number:"440"),
        Currency(code:"LVL",decimals:2,name:"Latvian lats",number:"428"),
        Currency(code:"LYD",decimals:3,name:"Libyan dinar",number:"434"),
        Currency(code:"MAD",decimals:2,name:"Moroccan dirham",number:"504"),
        Currency(code:"MDL",decimals:2,name:"Moldovan leu",number:"498"),
        Currency(code:"MGA",decimals:0,name:"Malagasy ariary",number:"969"),
        Currency(code:"MKD",decimals:0,name:"Macedonian denar",number:"807"),
        Currency(code:"MMK",decimals:0,name:"Myanma kyat",number:"104"),
        Currency(code:"MNT",decimals:2,name:"Mongolian tugrik",number:"496"),
        Currency(code:"MOP",decimals:2,name:"Macanese pataca",number:"446"),
        Currency(code:"MRO",decimals:0,name:"Mauritanian ouguiya",number:"478"),
        Currency(code:"MUR",decimals:2,name:"Mauritian rupee",number:"480"),
        Currency(code:"MVR",decimals:2,name:"Maldivian rufiyaa",number:"462"),
        Currency(code:"MWK",decimals:2,name:"Malawian kwacha",number:"454"),
        Currency(code:"MXN",decimals:2,name:"Mexican peso",number:"484"),
        Currency(code:"MXV",decimals:2,name:"Mexican Unidad de Inversion (UDI) (funds code)",number:"979"),
        Currency(code:"MYR",decimals:2,name:"Malaysian ringgit",number:"458"),
        Currency(code:"MZN",decimals:2,name:"Mozambican metical",number:"943"),
        Currency(code:"NAD",decimals:2,name:"Namibian dollar",number:"516"),
        Currency(code:"NGN",decimals:2,name:"Nigerian naira",number:"566"),
        Currency(code:"NIO",decimals:2,name:"Nicaraguan córdoba",number:"558"),
        Currency(code:"NOK",decimals:2,name:"Norwegian krone",number:"578"),
        Currency(code:"NPR",decimals:2,name:"Nepalese rupee",number:"524"),
        Currency(code:"NZD",decimals:2,name:"New Zealand dollar",number:"554"),
        Currency(code:"OMR",decimals:3,name:"Omani rial",number:"512"),
        Currency(code:"PAB",decimals:2,name:"Panamanian balboa",number:"590"),
        Currency(code:"PEN",decimals:2,name:"Peruvian nuevo sol",number:"604"),
        Currency(code:"PGK",decimals:2,name:"Papua New Guinean kina",number:"598"),
        Currency(code:"PHP",decimals:2,name:"Philippine peso",number:"608"),
        Currency(code:"PKR",decimals:2,name:"Pakistani rupee",number:"586"),
        Currency(code:"PLN",decimals:2,name:"Polish złoty",number:"985"),
        Currency(code:"PYG",decimals:0,name:"Paraguayan guaraní",number:"600"),
        Currency(code:"QAR",decimals:2,name:"Qatari riyal",number:"634"),
        Currency(code:"RON",decimals:2,name:"Romanian new leu",number:"946"),
        Currency(code:"RSD",decimals:2,name:"Serbian dinar",number:"941"),
        Currency(code:"RUB",decimals:2,name:"Russian rouble",number:"643"),
        Currency(code:"RWF",decimals:0,name:"Rwandan franc",number:"646"),
        Currency(code:"SAR",decimals:2,name:"Saudi riyal",number:"682"),
        Currency(code:"SBD",decimals:2,name:"Solomon Islands dollar",number:"90"),
        Currency(code:"SCR",decimals:2,name:"Seychelles rupee",number:"690"),
        Currency(code:"SDG",decimals:2,name:"Sudanese pound",number:"938"),
        Currency(code:"SEK",decimals:2,name:"Swedish krona/kronor",number:"752"),
        Currency(code:"SGD",decimals:2,name:"Singapore dollar",number:"702"),
        Currency(code:"SHP",decimals:2,name:"Saint Helena pound",number:"654"),
        Currency(code:"SLL",decimals:0,name:"Sierra Leonean leone",number:"694"),
        Currency(code:"SOS",decimals:2,name:"Somali shilling",number:"706"),
        Currency(code:"SRD",decimals:2,name:"Surinamese dollar",number:"968"),
        Currency(code:"SSP",decimals:2,name:"South Sudanese pound",number:"728"),
        Currency(code:"STD",decimals:0,name:"São Tomé and Príncipe dobra",number:"678"),
        Currency(code:"SYP",decimals:2,name:"Syrian pound",number:"760"),
        Currency(code:"SZL",decimals:2,name:"Swazi lilangeni",number:"748"),
        Currency(code:"THB",decimals:2,name:"Thai baht",number:"764"),
        Currency(code:"TJS",decimals:2,name:"Tajikistani somoni",number:"972"),
        Currency(code:"TMT",decimals:2,name:"Turkmenistani manat",number:"934"),
        Currency(code:"TND",decimals:3,name:"Tunisian dinar",number:"788"),
        Currency(code:"TOP",decimals:2,name:"Tongan paʻanga",number:"776"),
        Currency(code:"TRY",decimals:2,name:"Turkish lira",number:"949"),
        Currency(code:"TTD",decimals:2,name:"Trinidad and Tobago dollar",number:"780"),
        Currency(code:"TWD",decimals:2,name:"New Taiwan dollar",number:"901"),
        Currency(code:"TZS",decimals:2,name:"Tanzanian shilling",number:"834"),
        Currency(code:"UAH",decimals:2,name:"Ukrainian hryvnia",number:"980"),
        Currency(code:"UGX",decimals:2,name:"Ugandan shilling",number:"800"),
        Currency(code:"USD",decimals:2,name:"United States dollar",number:"840"),
        Currency(code:"USN",decimals:2,name:"United States dollar (next day) (funds code)",number:"997"),
        Currency(code:"USS",decimals:2,name:"United States dollar (same day) (funds code) (one source[who?] claims it is no longer used, but it is still on the ISO 4217-MA list)",number:"998"),
        Currency(code:"UYI",decimals:0,name:"Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)",number:"940"),
        Currency(code:"UYU",decimals:2,name:"Uruguayan peso",number:"858"),
        Currency(code:"UZS",decimals:2,name:"Uzbekistan som",number:"860"),
        Currency(code:"VEF",decimals:2,name:"Venezuelan bolívar fuerte",number:"937"),
        Currency(code:"VND",decimals:0,name:"Vietnamese dong",number:"704"),
        Currency(code:"VUV",decimals:0,name:"Vanuatu vatu",number:"548"),
        Currency(code:"WST",decimals:2,name:"Samoan tala",number:"882"),
        Currency(code:"XAF",decimals:0,name:"CFA franc BEAC",number:"950"),
        Currency(code:"XAG",decimals:0,name:"Silver (one troy ounce)",number:"961"),
        Currency(code:"XAU",decimals:0,name:"Gold (one troy ounce)",number:"959"),
        Currency(code:"XBA",decimals:0,name:"European Composite Unit (EURCO) (bond market unit)",number:"955"),
        Currency(code:"XBB",decimals:0,name:"European Monetary Unit (E.M.U.-6) (bond market unit)",number:"956"),
        Currency(code:"XBC",decimals:0,name:"European Unit of Account 9 (E.U.A.-9) (bond market unit)",number:"957"),
        Currency(code:"XBD",decimals:0,name:"European Unit of Account 17 (E.U.A.-17) (bond market unit)",number:"958"),
        Currency(code:"XCD",decimals:2,name:"East Caribbean dollar",number:"951"),
        Currency(code:"XDR",decimals:0,name:"Special drawing rights",number:"960"),
        Currency(code:"XFU",decimals:0,name:"UIC franc (special settlement currency)",number:"Nil"),
        Currency(code:"XOF",decimals:0,name:"CFA franc BCEAO",number:"952"),
        Currency(code:"XPD",decimals:0,name:"Palladium (one troy ounce)",number:"964"),
        Currency(code:"XPF",decimals:0,name:"CFP franc",number:"953"),
        Currency(code:"XPT",decimals:0,name:"Platinum (one troy ounce)",number:"962"),
        Currency(code:"XTS",decimals:0,name:"Code reserved for testing purposes",number:"963"),
        Currency(code:"XXX",decimals:0,name:"No currency",number:"999"),
        Currency(code:"YER",decimals:2,name:"Yemeni rial",number:"886"),
        Currency(code:"ZAR",decimals:2,name:"South African rand",number:"710"),
        Currency(code:"ZMW",decimals:2,name:"Zambian kwacha",number:"967")
    ]
}



