//
//  Language.swift
//  BBServices
//
//  Created by Nitin kachhadiya on 26/09/20.
//  Copyright © 2020 Nitin kachhadiya. All rights reserved.
//

import Foundation

public struct Language : Hashable, Codable, Identifiable  {
    public let id = UUID()
    public let alpha2, alpha3, bibliographic, name: String
}

public typealias Languages = [Language]

extension Language {

    public static let languages: [Language] = [
        Language(alpha2:"aa",alpha3:"aar",bibliographic:"",name:"Afar"),
        Language(alpha2:"ab",alpha3:"abk",bibliographic:"",name:"Abkhazian"),
        Language(alpha2:"",alpha3:"ace",bibliographic:"",name:"Achinese"),
        Language(alpha2:"",alpha3:"ach",bibliographic:"",name:"Acoli"),
        Language(alpha2:"",alpha3:"ada",bibliographic:"",name:"Adangme"),
        Language(alpha2:"",alpha3:"ady",bibliographic:"",name:"Adygei"),
        Language(alpha2:"",alpha3:"ady",bibliographic:"",name:"Adyghe"),
        Language(alpha2:"",alpha3:"afa",bibliographic:"",name:"Afro-Asiatic languages"),
        Language(alpha2:"",alpha3:"afh",bibliographic:"",name:"Afrihili"),
        Language(alpha2:"af",alpha3:"afr",bibliographic:"",name:"Afrikaans"),
        Language(alpha2:"",alpha3:"ain",bibliographic:"",name:"Ainu"),
        Language(alpha2:"ak",alpha3:"aka",bibliographic:"",name:"Akan"),
        Language(alpha2:"",alpha3:"akk",bibliographic:"",name:"Akkadian"),
        Language(alpha2:"",alpha3:"ale",bibliographic:"",name:"Aleut"),
        Language(alpha2:"",alpha3:"alg",bibliographic:"",name:"Algonquian languages"),
        Language(alpha2:"",alpha3:"alt",bibliographic:"",name:"Southern Altai"),
        Language(alpha2:"am",alpha3:"amh",bibliographic:"",name:"Amharic"),
        Language(alpha2:"",alpha3:"ang",bibliographic:"",name:"English, Old (ca.450-1100)"),
        Language(alpha2:"",alpha3:"anp",bibliographic:"",name:"Angika"),
        Language(alpha2:"",alpha3:"apa",bibliographic:"",name:"Apache languages"),
        Language(alpha2:"ar",alpha3:"ara",bibliographic:"",name:"Arabic"),
        Language(alpha2:"",alpha3:"arc",bibliographic:"",name:"Imperial Aramaic (700-300 BCE)"),
        Language(alpha2:"",alpha3:"arc",bibliographic:"",name:"Official Aramaic (700-300 BCE)"),
        Language(alpha2:"an",alpha3:"arg",bibliographic:"",name:"Aragonese"),
        Language(alpha2:"",alpha3:"arn",bibliographic:"",name:"Mapuche"),
        Language(alpha2:"",alpha3:"arn",bibliographic:"",name:"Mapudungun"),
        Language(alpha2:"",alpha3:"arp",bibliographic:"",name:"Arapaho"),
        Language(alpha2:"",alpha3:"art",bibliographic:"",name:"Artificial languages"),
        Language(alpha2:"",alpha3:"arw",bibliographic:"",name:"Arawak"),
        Language(alpha2:"as",alpha3:"asm",bibliographic:"",name:"Assamese"),
        Language(alpha2:"",alpha3:"ast",bibliographic:"",name:"Asturian"),
        Language(alpha2:"",alpha3:"ast",bibliographic:"",name:"Asturleonese"),
        Language(alpha2:"",alpha3:"ast",bibliographic:"",name:"Bable"),
        Language(alpha2:"",alpha3:"ast",bibliographic:"",name:"Leonese"),
        Language(alpha2:"",alpha3:"ath",bibliographic:"",name:"Athapascan languages"),
        Language(alpha2:"",alpha3:"aus",bibliographic:"",name:"Australian languages"),
        Language(alpha2:"av",alpha3:"ava",bibliographic:"",name:"Avaric"),
        Language(alpha2:"ae",alpha3:"ave",bibliographic:"",name:"Avestan"),
        Language(alpha2:"",alpha3:"awa",bibliographic:"",name:"Awadhi"),
        Language(alpha2:"ay",alpha3:"aym",bibliographic:"",name:"Aymara"),
        Language(alpha2:"az",alpha3:"aze",bibliographic:"",name:"Azerbaijani"),
        Language(alpha2:"",alpha3:"bad",bibliographic:"",name:"Banda languages"),
        Language(alpha2:"",alpha3:"bai",bibliographic:"",name:"Bamileke languages"),
        Language(alpha2:"ba",alpha3:"bak",bibliographic:"",name:"Bashkir"),
        Language(alpha2:"",alpha3:"bal",bibliographic:"",name:"Baluchi"),
        Language(alpha2:"bm",alpha3:"bam",bibliographic:"",name:"Bambara"),
        Language(alpha2:"",alpha3:"ban",bibliographic:"",name:"Balinese"),
        Language(alpha2:"",alpha3:"bas",bibliographic:"",name:"Basa"),
        Language(alpha2:"",alpha3:"bat",bibliographic:"",name:"Baltic languages"),
        Language(alpha2:"",alpha3:"bej",bibliographic:"",name:"Bedawiyet"),
        Language(alpha2:"",alpha3:"bej",bibliographic:"",name:"Beja"),
        Language(alpha2:"be",alpha3:"bel",bibliographic:"",name:"Belarusian"),
        Language(alpha2:"",alpha3:"bem",bibliographic:"",name:"Bemba"),
        Language(alpha2:"bn",alpha3:"ben",bibliographic:"",name:"Bengali"),
        Language(alpha2:"",alpha3:"ber",bibliographic:"",name:"Berber languages"),
        Language(alpha2:"",alpha3:"bho",bibliographic:"",name:"Bhojpuri"),
        Language(alpha2:"bh",alpha3:"bih",bibliographic:"",name:"Bihari languages"),
        Language(alpha2:"",alpha3:"bik",bibliographic:"",name:"Bikol"),
        Language(alpha2:"",alpha3:"bin",bibliographic:"",name:"Bini"),
        Language(alpha2:"",alpha3:"bin",bibliographic:"",name:"Edo"),
        Language(alpha2:"bi",alpha3:"bis",bibliographic:"",name:"Bislama"),
        Language(alpha2:"",alpha3:"bla",bibliographic:"",name:"Siksika"),
        Language(alpha2:"",alpha3:"bnt",bibliographic:"",name:"Bantu languages"),
        Language(alpha2:"bo",alpha3:"bod",bibliographic:"tib",name:"Tibetan"),
        Language(alpha2:"bs",alpha3:"bos",bibliographic:"",name:"Bosnian"),
        Language(alpha2:"",alpha3:"bra",bibliographic:"",name:"Braj"),
        Language(alpha2:"br",alpha3:"bre",bibliographic:"",name:"Breton"),
        Language(alpha2:"",alpha3:"btk",bibliographic:"",name:"Batak languages"),
        Language(alpha2:"",alpha3:"bua",bibliographic:"",name:"Buriat"),
        Language(alpha2:"",alpha3:"bug",bibliographic:"",name:"Buginese"),
        Language(alpha2:"bg",alpha3:"bul",bibliographic:"",name:"Bulgarian"),
        Language(alpha2:"",alpha3:"byn",bibliographic:"",name:"Bilin"),
        Language(alpha2:"",alpha3:"byn",bibliographic:"",name:"Blin"),
        Language(alpha2:"",alpha3:"cad",bibliographic:"",name:"Caddo"),
        Language(alpha2:"",alpha3:"cai",bibliographic:"",name:"Central American Indian languages"),
        Language(alpha2:"",alpha3:"car",bibliographic:"",name:"Galibi Carib"),
        Language(alpha2:"ca",alpha3:"cat",bibliographic:"",name:"Catalan"),
        Language(alpha2:"ca",alpha3:"cat",bibliographic:"",name:"Valencian"),
        Language(alpha2:"",alpha3:"cau",bibliographic:"",name:"Caucasian languages"),
        Language(alpha2:"",alpha3:"ceb",bibliographic:"",name:"Cebuano"),
        Language(alpha2:"",alpha3:"cel",bibliographic:"",name:"Celtic languages"),
        Language(alpha2:"cs",alpha3:"ces",bibliographic:"cze",name:"Czech"),
        Language(alpha2:"ch",alpha3:"cha",bibliographic:"",name:"Chamorro"),
        Language(alpha2:"",alpha3:"chb",bibliographic:"",name:"Chibcha"),
        Language(alpha2:"ce",alpha3:"che",bibliographic:"",name:"Chechen"),
        Language(alpha2:"",alpha3:"chg",bibliographic:"",name:"Chagatai"),
        Language(alpha2:"",alpha3:"chk",bibliographic:"",name:"Chuukese"),
        Language(alpha2:"",alpha3:"chm",bibliographic:"",name:"Mari"),
        Language(alpha2:"",alpha3:"chn",bibliographic:"",name:"Chinook jargon"),
        Language(alpha2:"",alpha3:"cho",bibliographic:"",name:"Choctaw"),
        Language(alpha2:"",alpha3:"chp",bibliographic:"",name:"Chipewyan"),
        Language(alpha2:"",alpha3:"chp",bibliographic:"",name:"Dene Suline"),
        Language(alpha2:"",alpha3:"chr",bibliographic:"",name:"Cherokee"),
        Language(alpha2:"cu",alpha3:"chu",bibliographic:"",name:"Church Slavic"),
        Language(alpha2:"cu",alpha3:"chu",bibliographic:"",name:"Church Slavonic"),
        Language(alpha2:"cu",alpha3:"chu",bibliographic:"",name:"Old Bulgarian"),
        Language(alpha2:"cu",alpha3:"chu",bibliographic:"",name:"Old Church Slavonic"),
        Language(alpha2:"cu",alpha3:"chu",bibliographic:"",name:"Old Slavonic"),
        Language(alpha2:"cv",alpha3:"chv",bibliographic:"",name:"Chuvash"),
        Language(alpha2:"",alpha3:"chy",bibliographic:"",name:"Cheyenne"),
        Language(alpha2:"",alpha3:"cmc",bibliographic:"",name:"Chamic languages"),
        Language(alpha2:"",alpha3:"cop",bibliographic:"",name:"Coptic"),
        Language(alpha2:"kw",alpha3:"cor",bibliographic:"",name:"Cornish"),
        Language(alpha2:"co",alpha3:"cos",bibliographic:"",name:"Corsican"),
        Language(alpha2:"",alpha3:"cpe",bibliographic:"",name:"Creoles and pidgins, English based"),
        Language(alpha2:"",alpha3:"cpf",bibliographic:"",name:"Creoles and pidgins, French-based"),
        Language(alpha2:"",alpha3:"cpp",bibliographic:"",name:"Creoles and pidgins, Portuguese-based"),
        Language(alpha2:"cr",alpha3:"cre",bibliographic:"",name:"Cree"),
        Language(alpha2:"",alpha3:"crh",bibliographic:"",name:"Crimean Tatar"),
        Language(alpha2:"",alpha3:"crh",bibliographic:"",name:"Crimean Turkish"),
        Language(alpha2:"",alpha3:"crp",bibliographic:"",name:"Creoles and pidgins"),
        Language(alpha2:"",alpha3:"csb",bibliographic:"",name:"Kashubian"),
        Language(alpha2:"",alpha3:"cus",bibliographic:"",name:"Cushitic languages"),
        Language(alpha2:"cy",alpha3:"cym",bibliographic:"wel",name:"Welsh"),
        Language(alpha2:"",alpha3:"dak",bibliographic:"",name:"Dakota"),
        Language(alpha2:"da",alpha3:"dan",bibliographic:"",name:"Danish"),
        Language(alpha2:"",alpha3:"dar",bibliographic:"",name:"Dargwa"),
        Language(alpha2:"",alpha3:"day",bibliographic:"",name:"Land Dayak languages"),
        Language(alpha2:"",alpha3:"del",bibliographic:"",name:"Delaware"),
        Language(alpha2:"",alpha3:"den",bibliographic:"",name:"Slave (Athapascan)"),
        Language(alpha2:"de",alpha3:"deu",bibliographic:"ger",name:"German"),
        Language(alpha2:"",alpha3:"dgr",bibliographic:"",name:"Dogrib"),
        Language(alpha2:"",alpha3:"din",bibliographic:"",name:"Dinka"),
        Language(alpha2:"dv",alpha3:"div",bibliographic:"",name:"Dhivehi"),
        Language(alpha2:"dv",alpha3:"div",bibliographic:"",name:"Divehi"),
        Language(alpha2:"dv",alpha3:"div",bibliographic:"",name:"Maldivian"),
        Language(alpha2:"",alpha3:"doi",bibliographic:"",name:"Dogri"),
        Language(alpha2:"",alpha3:"dra",bibliographic:"",name:"Dravidian languages"),
        Language(alpha2:"",alpha3:"dsb",bibliographic:"",name:"Lower Sorbian"),
        Language(alpha2:"",alpha3:"dua",bibliographic:"",name:"Duala"),
        Language(alpha2:"",alpha3:"dum",bibliographic:"",name:"Dutch, Middle (ca.1050-1350)"),
        Language(alpha2:"",alpha3:"dyu",bibliographic:"",name:"Dyula"),
        Language(alpha2:"dz",alpha3:"dzo",bibliographic:"",name:"Dzongkha"),
        Language(alpha2:"",alpha3:"efi",bibliographic:"",name:"Efik"),
        Language(alpha2:"",alpha3:"egy",bibliographic:"",name:"Egyptian (Ancient)"),
        Language(alpha2:"",alpha3:"eka",bibliographic:"",name:"Ekajuk"),
        Language(alpha2:"el",alpha3:"ell",bibliographic:"gre",name:"Greek, Modern (1453-)"),
        Language(alpha2:"",alpha3:"elx",bibliographic:"",name:"Elamite"),
        Language(alpha2:"en",alpha3:"eng",bibliographic:"",name:"English"),
        Language(alpha2:"",alpha3:"enm",bibliographic:"",name:"English, Middle (1100-1500)"),
        Language(alpha2:"eo",alpha3:"epo",bibliographic:"",name:"Esperanto"),
        Language(alpha2:"et",alpha3:"est",bibliographic:"",name:"Estonian"),
        Language(alpha2:"eu",alpha3:"eus",bibliographic:"baq",name:"Basque"),
        Language(alpha2:"ee",alpha3:"ewe",bibliographic:"",name:"Ewe"),
        Language(alpha2:"",alpha3:"ewo",bibliographic:"",name:"Ewondo"),
        Language(alpha2:"",alpha3:"fan",bibliographic:"",name:"Fang"),
        Language(alpha2:"fo",alpha3:"fao",bibliographic:"",name:"Faroese"),
        Language(alpha2:"fa",alpha3:"fas",bibliographic:"per",name:"Persian"),
        Language(alpha2:"",alpha3:"fat",bibliographic:"",name:"Fanti"),
        Language(alpha2:"fj",alpha3:"fij",bibliographic:"",name:"Fijian"),
        Language(alpha2:"",alpha3:"fil",bibliographic:"",name:"Filipino"),
        Language(alpha2:"",alpha3:"fil",bibliographic:"",name:"Pilipino"),
        Language(alpha2:"fi",alpha3:"fin",bibliographic:"",name:"Finnish"),
        Language(alpha2:"",alpha3:"fiu",bibliographic:"",name:"Finno-Ugrian languages"),
        Language(alpha2:"",alpha3:"fon",bibliographic:"",name:"Fon"),
        Language(alpha2:"fr",alpha3:"fra",bibliographic:"fre",name:"French"),
        Language(alpha2:"",alpha3:"frm",bibliographic:"",name:"French, Middle (ca.1400-1600)"),
        Language(alpha2:"",alpha3:"fro",bibliographic:"",name:"French, Old (842-ca.1400)"),
        Language(alpha2:"",alpha3:"frr",bibliographic:"",name:"Northern Frisian"),
        Language(alpha2:"",alpha3:"frs",bibliographic:"",name:"Eastern Frisian"),
        Language(alpha2:"fy",alpha3:"fry",bibliographic:"",name:"Western Frisian"),
        Language(alpha2:"ff",alpha3:"ful",bibliographic:"",name:"Fulah"),
        Language(alpha2:"",alpha3:"fur",bibliographic:"",name:"Friulian"),
        Language(alpha2:"",alpha3:"gaa",bibliographic:"",name:"Ga"),
        Language(alpha2:"",alpha3:"gay",bibliographic:"",name:"Gayo"),
        Language(alpha2:"",alpha3:"gba",bibliographic:"",name:"Gbaya"),
        Language(alpha2:"",alpha3:"gem",bibliographic:"",name:"Germanic languages"),
        Language(alpha2:"",alpha3:"gez",bibliographic:"",name:"Geez"),
        Language(alpha2:"",alpha3:"gil",bibliographic:"",name:"Gilbertese"),
        Language(alpha2:"gd",alpha3:"gla",bibliographic:"",name:"Gaelic"),
        Language(alpha2:"gd",alpha3:"gla",bibliographic:"",name:"Scottish Gaelic"),
        Language(alpha2:"ga",alpha3:"gle",bibliographic:"",name:"Irish"),
        Language(alpha2:"gl",alpha3:"glg",bibliographic:"",name:"Galician"),
        Language(alpha2:"gv",alpha3:"glv",bibliographic:"",name:"Manx"),
        Language(alpha2:"",alpha3:"gmh",bibliographic:"",name:"German, Middle High (ca.1050-1500)"),
        Language(alpha2:"",alpha3:"goh",bibliographic:"",name:"German, Old High (ca.750-1050)"),
        Language(alpha2:"",alpha3:"gon",bibliographic:"",name:"Gondi"),
        Language(alpha2:"",alpha3:"gor",bibliographic:"",name:"Gorontalo"),
        Language(alpha2:"",alpha3:"got",bibliographic:"",name:"Gothic"),
        Language(alpha2:"",alpha3:"grb",bibliographic:"",name:"Grebo"),
        Language(alpha2:"",alpha3:"grc",bibliographic:"",name:"Greek, Ancient (to 1453)"),
        Language(alpha2:"gn",alpha3:"grn",bibliographic:"",name:"Guarani"),
        Language(alpha2:"",alpha3:"gsw",bibliographic:"",name:"Alemannic"),
        Language(alpha2:"",alpha3:"gsw",bibliographic:"",name:"Alsatian"),
        Language(alpha2:"",alpha3:"gsw",bibliographic:"",name:"Swiss German"),
        Language(alpha2:"gu",alpha3:"guj",bibliographic:"",name:"Gujarati"),
        Language(alpha2:"",alpha3:"gwi",bibliographic:"",name:"Gwich'in"),
        Language(alpha2:"",alpha3:"hai",bibliographic:"",name:"Haida"),
        Language(alpha2:"ht",alpha3:"hat",bibliographic:"",name:"Haitian"),
        Language(alpha2:"ht",alpha3:"hat",bibliographic:"",name:"Haitian Creole"),
        Language(alpha2:"ha",alpha3:"hau",bibliographic:"",name:"Hausa"),
        Language(alpha2:"",alpha3:"haw",bibliographic:"",name:"Hawaiian"),
        Language(alpha2:"he",alpha3:"heb",bibliographic:"",name:"Hebrew"),
        Language(alpha2:"hz",alpha3:"her",bibliographic:"",name:"Herero"),
        Language(alpha2:"",alpha3:"hil",bibliographic:"",name:"Hiligaynon"),
        Language(alpha2:"",alpha3:"him",bibliographic:"",name:"Himachali languages"),
        Language(alpha2:"",alpha3:"him",bibliographic:"",name:"Western Pahari languages"),
        Language(alpha2:"hi",alpha3:"hin",bibliographic:"",name:"Hindi"),
        Language(alpha2:"",alpha3:"hit",bibliographic:"",name:"Hittite"),
        Language(alpha2:"",alpha3:"hmn",bibliographic:"",name:"Hmong"),
        Language(alpha2:"",alpha3:"hmn",bibliographic:"",name:"Mong"),
        Language(alpha2:"ho",alpha3:"hmo",bibliographic:"",name:"Hiri Motu"),
        Language(alpha2:"hr",alpha3:"hrv",bibliographic:"",name:"Croatian"),
        Language(alpha2:"",alpha3:"hsb",bibliographic:"",name:"Upper Sorbian"),
        Language(alpha2:"hu",alpha3:"hun",bibliographic:"",name:"Hungarian"),
        Language(alpha2:"",alpha3:"hup",bibliographic:"",name:"Hupa"),
        Language(alpha2:"hy",alpha3:"hye",bibliographic:"arm",name:"Armenian"),
        Language(alpha2:"",alpha3:"iba",bibliographic:"",name:"Iban"),
        Language(alpha2:"ig",alpha3:"ibo",bibliographic:"",name:"Igbo"),
        Language(alpha2:"io",alpha3:"ido",bibliographic:"",name:"Ido"),
        Language(alpha2:"ii",alpha3:"iii",bibliographic:"",name:"Nuosu"),
        Language(alpha2:"ii",alpha3:"iii",bibliographic:"",name:"Sichuan Yi"),
        Language(alpha2:"",alpha3:"ijo",bibliographic:"",name:"Ijo languages"),
        Language(alpha2:"iu",alpha3:"iku",bibliographic:"",name:"Inuktitut"),
        Language(alpha2:"ie",alpha3:"ile",bibliographic:"",name:"Interlingue"),
        Language(alpha2:"ie",alpha3:"ile",bibliographic:"",name:"Occidental"),
        Language(alpha2:"",alpha3:"ilo",bibliographic:"",name:"Iloko"),
        Language(alpha2:"ia",alpha3:"ina",bibliographic:"",name:"Interlingua (International Auxiliary Language Association)"),
        Language(alpha2:"",alpha3:"inc",bibliographic:"",name:"Indic languages"),
        Language(alpha2:"id",alpha3:"ind",bibliographic:"",name:"Indonesian"),
        Language(alpha2:"",alpha3:"ine",bibliographic:"",name:"Indo-European languages"),
        Language(alpha2:"",alpha3:"inh",bibliographic:"",name:"Ingush"),
        Language(alpha2:"ik",alpha3:"ipk",bibliographic:"",name:"Inupiaq"),
        Language(alpha2:"",alpha3:"ira",bibliographic:"",name:"Iranian languages"),
        Language(alpha2:"",alpha3:"iro",bibliographic:"",name:"Iroquoian languages"),
        Language(alpha2:"is",alpha3:"isl",bibliographic:"ice",name:"Icelandic"),
        Language(alpha2:"it",alpha3:"ita",bibliographic:"",name:"Italian"),
        Language(alpha2:"jv",alpha3:"jav",bibliographic:"",name:"Javanese"),
        Language(alpha2:"",alpha3:"jbo",bibliographic:"",name:"Lojban"),
        Language(alpha2:"ja",alpha3:"jpn",bibliographic:"",name:"Japanese"),
        Language(alpha2:"",alpha3:"jpr",bibliographic:"",name:"Judeo-Persian"),
        Language(alpha2:"",alpha3:"jrb",bibliographic:"",name:"Judeo-Arabic"),
        Language(alpha2:"",alpha3:"kaa",bibliographic:"",name:"Kara-Kalpak"),
        Language(alpha2:"",alpha3:"kab",bibliographic:"",name:"Kabyle"),
        Language(alpha2:"",alpha3:"kac",bibliographic:"",name:"Jingpho"),
        Language(alpha2:"",alpha3:"kac",bibliographic:"",name:"Kachin"),
        Language(alpha2:"kl",alpha3:"kal",bibliographic:"",name:"Greenlandic"),
        Language(alpha2:"kl",alpha3:"kal",bibliographic:"",name:"Kalaallisut"),
        Language(alpha2:"",alpha3:"kam",bibliographic:"",name:"Kamba"),
        Language(alpha2:"kn",alpha3:"kan",bibliographic:"",name:"Kannada"),
        Language(alpha2:"",alpha3:"kar",bibliographic:"",name:"Karen languages"),
        Language(alpha2:"ks",alpha3:"kas",bibliographic:"",name:"Kashmiri"),
        Language(alpha2:"ka",alpha3:"kat",bibliographic:"geo",name:"Georgian"),
        Language(alpha2:"kr",alpha3:"kau",bibliographic:"",name:"Kanuri"),
        Language(alpha2:"",alpha3:"kaw",bibliographic:"",name:"Kawi"),
        Language(alpha2:"kk",alpha3:"kaz",bibliographic:"",name:"Kazakh"),
        Language(alpha2:"",alpha3:"kbd",bibliographic:"",name:"Kabardian"),
        Language(alpha2:"",alpha3:"kha",bibliographic:"",name:"Khasi"),
        Language(alpha2:"",alpha3:"khi",bibliographic:"",name:"Khoisan languages"),
        Language(alpha2:"km",alpha3:"khm",bibliographic:"",name:"Central Khmer"),
        Language(alpha2:"",alpha3:"kho",bibliographic:"",name:"Khotanese"),
        Language(alpha2:"",alpha3:"kho",bibliographic:"",name:"Sakan"),
        Language(alpha2:"ki",alpha3:"kik",bibliographic:"",name:"Gikuyu"),
        Language(alpha2:"ki",alpha3:"kik",bibliographic:"",name:"Kikuyu"),
        Language(alpha2:"rw",alpha3:"kin",bibliographic:"",name:"Kinyarwanda"),
        Language(alpha2:"ky",alpha3:"kir",bibliographic:"",name:"Kirghiz"),
        Language(alpha2:"ky",alpha3:"kir",bibliographic:"",name:"Kyrgyz"),
        Language(alpha2:"",alpha3:"kmb",bibliographic:"",name:"Kimbundu"),
        Language(alpha2:"",alpha3:"kok",bibliographic:"",name:"Konkani"),
        Language(alpha2:"kv",alpha3:"kom",bibliographic:"",name:"Komi"),
        Language(alpha2:"kg",alpha3:"kon",bibliographic:"",name:"Kongo"),
        Language(alpha2:"ko",alpha3:"kor",bibliographic:"",name:"Korean"),
        Language(alpha2:"",alpha3:"kos",bibliographic:"",name:"Kosraean"),
        Language(alpha2:"",alpha3:"kpe",bibliographic:"",name:"Kpelle"),
        Language(alpha2:"",alpha3:"krc",bibliographic:"",name:"Karachay-Balkar"),
        Language(alpha2:"",alpha3:"krl",bibliographic:"",name:"Karelian"),
        Language(alpha2:"",alpha3:"kro",bibliographic:"",name:"Kru languages"),
        Language(alpha2:"",alpha3:"kru",bibliographic:"",name:"Kurukh"),
        Language(alpha2:"kj",alpha3:"kua",bibliographic:"",name:"Kuanyama"),
        Language(alpha2:"kj",alpha3:"kua",bibliographic:"",name:"Kwanyama"),
        Language(alpha2:"",alpha3:"kum",bibliographic:"",name:"Kumyk"),
        Language(alpha2:"ku",alpha3:"kur",bibliographic:"",name:"Kurdish"),
        Language(alpha2:"",alpha3:"kut",bibliographic:"",name:"Kutenai"),
        Language(alpha2:"",alpha3:"lad",bibliographic:"",name:"Ladino"),
        Language(alpha2:"",alpha3:"lah",bibliographic:"",name:"Lahnda"),
        Language(alpha2:"",alpha3:"lam",bibliographic:"",name:"Lamba"),
        Language(alpha2:"lo",alpha3:"lao",bibliographic:"",name:"Lao"),
        Language(alpha2:"la",alpha3:"lat",bibliographic:"",name:"Latin"),
        Language(alpha2:"lv",alpha3:"lav",bibliographic:"",name:"Latvian"),
        Language(alpha2:"",alpha3:"lez",bibliographic:"",name:"Lezghian"),
        Language(alpha2:"li",alpha3:"lim",bibliographic:"",name:"Limburgan"),
        Language(alpha2:"li",alpha3:"lim",bibliographic:"",name:"Limburger"),
        Language(alpha2:"li",alpha3:"lim",bibliographic:"",name:"Limburgish"),
        Language(alpha2:"ln",alpha3:"lin",bibliographic:"",name:"Lingala"),
        Language(alpha2:"lt",alpha3:"lit",bibliographic:"",name:"Lithuanian"),
        Language(alpha2:"",alpha3:"lol",bibliographic:"",name:"Mongo"),
        Language(alpha2:"",alpha3:"loz",bibliographic:"",name:"Lozi"),
        Language(alpha2:"lb",alpha3:"ltz",bibliographic:"",name:"Letzeburgesch"),
        Language(alpha2:"lb",alpha3:"ltz",bibliographic:"",name:"Luxembourgish"),
        Language(alpha2:"",alpha3:"lua",bibliographic:"",name:"Luba-Lulua"),
        Language(alpha2:"lu",alpha3:"lub",bibliographic:"",name:"Luba-Katanga"),
        Language(alpha2:"lg",alpha3:"lug",bibliographic:"",name:"Ganda"),
        Language(alpha2:"",alpha3:"lui",bibliographic:"",name:"Luiseno"),
        Language(alpha2:"",alpha3:"lun",bibliographic:"",name:"Lunda"),
        Language(alpha2:"",alpha3:"luo",bibliographic:"",name:"Luo (Kenya and Tanzania)"),
        Language(alpha2:"",alpha3:"lus",bibliographic:"",name:"Lushai"),
        Language(alpha2:"",alpha3:"mad",bibliographic:"",name:"Madurese"),
        Language(alpha2:"",alpha3:"mag",bibliographic:"",name:"Magahi"),
        Language(alpha2:"mh",alpha3:"mah",bibliographic:"",name:"Marshallese"),
        Language(alpha2:"",alpha3:"mai",bibliographic:"",name:"Maithili"),
        Language(alpha2:"",alpha3:"mak",bibliographic:"",name:"Makasar"),
        Language(alpha2:"ml",alpha3:"mal",bibliographic:"",name:"Malayalam"),
        Language(alpha2:"",alpha3:"man",bibliographic:"",name:"Mandingo"),
        Language(alpha2:"",alpha3:"map",bibliographic:"",name:"Austronesian languages"),
        Language(alpha2:"mr",alpha3:"mar",bibliographic:"",name:"Marathi"),
        Language(alpha2:"",alpha3:"mas",bibliographic:"",name:"Masai"),
        Language(alpha2:"",alpha3:"mdf",bibliographic:"",name:"Moksha"),
        Language(alpha2:"",alpha3:"mdr",bibliographic:"",name:"Mandar"),
        Language(alpha2:"",alpha3:"men",bibliographic:"",name:"Mende"),
        Language(alpha2:"",alpha3:"mga",bibliographic:"",name:"Irish, Middle (900-1200)"),
        Language(alpha2:"",alpha3:"mic",bibliographic:"",name:"Mi'kmaq"),
        Language(alpha2:"",alpha3:"mic",bibliographic:"",name:"Micmac"),
        Language(alpha2:"",alpha3:"min",bibliographic:"",name:"Minangkabau"),
        Language(alpha2:"",alpha3:"mis",bibliographic:"",name:"Uncoded languages"),
        Language(alpha2:"mk",alpha3:"mkd",bibliographic:"mac",name:"Macedonian"),
        Language(alpha2:"",alpha3:"mkh",bibliographic:"",name:"Mon-Khmer languages"),
        Language(alpha2:"mg",alpha3:"mlg",bibliographic:"",name:"Malagasy"),
        Language(alpha2:"mt",alpha3:"mlt",bibliographic:"",name:"Maltese"),
        Language(alpha2:"",alpha3:"mnc",bibliographic:"",name:"Manchu"),
        Language(alpha2:"",alpha3:"mni",bibliographic:"",name:"Manipuri"),
        Language(alpha2:"",alpha3:"mno",bibliographic:"",name:"Manobo languages"),
        Language(alpha2:"",alpha3:"moh",bibliographic:"",name:"Mohawk"),
        Language(alpha2:"mn",alpha3:"mon",bibliographic:"",name:"Mongolian"),
        Language(alpha2:"",alpha3:"mos",bibliographic:"",name:"Mossi"),
        Language(alpha2:"",alpha3:"mot",bibliographic:"",name:"Montenegrin"),
        Language(alpha2:"mi",alpha3:"mri",bibliographic:"mao",name:"Maori"),
        Language(alpha2:"ms",alpha3:"msa",bibliographic:"may",name:"Malay"),
        Language(alpha2:"",alpha3:"mul",bibliographic:"",name:"Multiple languages"),
        Language(alpha2:"",alpha3:"mun",bibliographic:"",name:"Munda languages"),
        Language(alpha2:"",alpha3:"mus",bibliographic:"",name:"Creek"),
        Language(alpha2:"",alpha3:"mwl",bibliographic:"",name:"Mirandese"),
        Language(alpha2:"",alpha3:"mwr",bibliographic:"",name:"Marwari"),
        Language(alpha2:"my",alpha3:"mya",bibliographic:"bur",name:"Burmese"),
        Language(alpha2:"",alpha3:"myn",bibliographic:"",name:"Mayan languages"),
        Language(alpha2:"",alpha3:"myv",bibliographic:"",name:"Erzya"),
        Language(alpha2:"",alpha3:"nah",bibliographic:"",name:"Nahuatl languages"),
        Language(alpha2:"",alpha3:"nai",bibliographic:"",name:"North American Indian languages"),
        Language(alpha2:"",alpha3:"nap",bibliographic:"",name:"Neapolitan"),
        Language(alpha2:"na",alpha3:"nau",bibliographic:"",name:"Nauru"),
        Language(alpha2:"nv",alpha3:"nav",bibliographic:"",name:"Navaho"),
        Language(alpha2:"nv",alpha3:"nav",bibliographic:"",name:"Navajo"),
        Language(alpha2:"nr",alpha3:"nbl",bibliographic:"",name:"Ndebele, South"),
        Language(alpha2:"nr",alpha3:"nbl",bibliographic:"",name:"South Ndebele"),
        Language(alpha2:"nd",alpha3:"nde",bibliographic:"",name:"Ndebele, North"),
        Language(alpha2:"nd",alpha3:"nde",bibliographic:"",name:"North Ndebele"),
        Language(alpha2:"ng",alpha3:"ndo",bibliographic:"",name:"Ndonga"),
        Language(alpha2:"",alpha3:"nds",bibliographic:"",name:"German, Low"),
        Language(alpha2:"",alpha3:"nds",bibliographic:"",name:"Low German"),
        Language(alpha2:"",alpha3:"nds",bibliographic:"",name:"Low Saxon"),
        Language(alpha2:"",alpha3:"nds",bibliographic:"",name:"Saxon, Low"),
        Language(alpha2:"ne",alpha3:"nep",bibliographic:"",name:"Nepali"),
        Language(alpha2:"",alpha3:"new",bibliographic:"",name:"Nepal Bhasa"),
        Language(alpha2:"",alpha3:"new",bibliographic:"",name:"Newari"),
        Language(alpha2:"",alpha3:"nia",bibliographic:"",name:"Nias"),
        Language(alpha2:"",alpha3:"nic",bibliographic:"",name:"Niger-Kordofanian languages"),
        Language(alpha2:"",alpha3:"niu",bibliographic:"",name:"Niuean"),
        Language(alpha2:"nl",alpha3:"nld",bibliographic:"dut",name:"Dutch"),
        Language(alpha2:"nl",alpha3:"nld",bibliographic:"dut",name:"Flemish"),
        Language(alpha2:"nn",alpha3:"nno",bibliographic:"",name:"Norwegian Nynorsk"),
        Language(alpha2:"nn",alpha3:"nno",bibliographic:"",name:"Nynorsk, Norwegian"),
        Language(alpha2:"nb",alpha3:"nob",bibliographic:"",name:"Bokmål, Norwegian"),
        Language(alpha2:"nb",alpha3:"nob",bibliographic:"",name:"Norwegian Bokmål"),
        Language(alpha2:"",alpha3:"nog",bibliographic:"",name:"Nogai"),
        Language(alpha2:"",alpha3:"non",bibliographic:"",name:"Norse, Old"),
        Language(alpha2:"no",alpha3:"nor",bibliographic:"",name:"Norwegian"),
        Language(alpha2:"",alpha3:"nqo",bibliographic:"",name:"N'Ko"),
        Language(alpha2:"",alpha3:"nso",bibliographic:"",name:"Northern Sotho"),
        Language(alpha2:"",alpha3:"nso",bibliographic:"",name:"Pedi"),
        Language(alpha2:"",alpha3:"nso",bibliographic:"",name:"Sepedi"),
        Language(alpha2:"",alpha3:"nso",bibliographic:"",name:"Sotho, Northern"),
        Language(alpha2:"",alpha3:"nub",bibliographic:"",name:"Nubian languages"),
        Language(alpha2:"",alpha3:"nwc",bibliographic:"",name:"Classical Nepal Bhasa"),
        Language(alpha2:"",alpha3:"nwc",bibliographic:"",name:"Classical Newari"),
        Language(alpha2:"",alpha3:"nwc",bibliographic:"",name:"Old Newari"),
        Language(alpha2:"ny",alpha3:"nya",bibliographic:"",name:"Chewa"),
        Language(alpha2:"ny",alpha3:"nya",bibliographic:"",name:"Chichewa"),
        Language(alpha2:"ny",alpha3:"nya",bibliographic:"",name:"Nyanja"),
        Language(alpha2:"",alpha3:"nym",bibliographic:"",name:"Nyamwezi"),
        Language(alpha2:"",alpha3:"nyn",bibliographic:"",name:"Nyankole"),
        Language(alpha2:"",alpha3:"nyo",bibliographic:"",name:"Nyoro"),
        Language(alpha2:"",alpha3:"nzi",bibliographic:"",name:"Nzima"),
        Language(alpha2:"oc",alpha3:"oci",bibliographic:"",name:"Occitan (post 1500)"),
        Language(alpha2:"oj",alpha3:"oji",bibliographic:"",name:"Ojibwa"),
        Language(alpha2:"or",alpha3:"ori",bibliographic:"",name:"Oriya"),
        Language(alpha2:"om",alpha3:"orm",bibliographic:"",name:"Oromo"),
        Language(alpha2:"",alpha3:"osa",bibliographic:"",name:"Osage"),
        Language(alpha2:"os",alpha3:"oss",bibliographic:"",name:"Ossetian"),
        Language(alpha2:"os",alpha3:"oss",bibliographic:"",name:"Ossetic"),
        Language(alpha2:"",alpha3:"ota",bibliographic:"",name:"Turkish, Ottoman (1500-1928)"),
        Language(alpha2:"",alpha3:"oto",bibliographic:"",name:"Otomian languages"),
        Language(alpha2:"",alpha3:"paa",bibliographic:"",name:"Papuan languages"),
        Language(alpha2:"",alpha3:"pag",bibliographic:"",name:"Pangasinan"),
        Language(alpha2:"",alpha3:"pal",bibliographic:"",name:"Pahlavi"),
        Language(alpha2:"",alpha3:"pam",bibliographic:"",name:"Kapampangan"),
        Language(alpha2:"",alpha3:"pam",bibliographic:"",name:"Pampanga"),
        Language(alpha2:"pa",alpha3:"pan",bibliographic:"",name:"Panjabi"),
        Language(alpha2:"pa",alpha3:"pan",bibliographic:"",name:"Punjabi"),
        Language(alpha2:"",alpha3:"pap",bibliographic:"",name:"Papiamento"),
        Language(alpha2:"",alpha3:"pau",bibliographic:"",name:"Palauan"),
        Language(alpha2:"",alpha3:"peo",bibliographic:"",name:"Persian, Old (ca.600-400 B.C.)"),
        Language(alpha2:"",alpha3:"phi",bibliographic:"",name:"Philippine languages"),
        Language(alpha2:"",alpha3:"phn",bibliographic:"",name:"Phoenician"),
        Language(alpha2:"pi",alpha3:"pli",bibliographic:"",name:"Pali"),
        Language(alpha2:"pl",alpha3:"pol",bibliographic:"",name:"Polish"),
        Language(alpha2:"",alpha3:"pon",bibliographic:"",name:"Pohnpeian"),
        Language(alpha2:"pt",alpha3:"por",bibliographic:"",name:"Portuguese"),
        Language(alpha2:"",alpha3:"pra",bibliographic:"",name:"Prakrit languages"),
        Language(alpha2:"",alpha3:"pro",bibliographic:"",name:"Occitan, Old (to 1500)"),
        Language(alpha2:"",alpha3:"pro",bibliographic:"",name:"Provençal, Old (to 1500)"),
        Language(alpha2:"ps",alpha3:"pus",bibliographic:"",name:"Pashto"),
        Language(alpha2:"ps",alpha3:"pus",bibliographic:"",name:"Pushto"),
        Language(alpha2:"qu",alpha3:"que",bibliographic:"",name:"Quechua"),
        Language(alpha2:"",alpha3:"raj",bibliographic:"",name:"Rajasthani"),
        Language(alpha2:"",alpha3:"rap",bibliographic:"",name:"Rapanui"),
        Language(alpha2:"",alpha3:"rar",bibliographic:"",name:"Cook Islands Maori"),
        Language(alpha2:"",alpha3:"rar",bibliographic:"",name:"Rarotongan"),
        Language(alpha2:"",alpha3:"roa",bibliographic:"",name:"Romance languages"),
        Language(alpha2:"rm",alpha3:"roh",bibliographic:"",name:"Romansh"),
        Language(alpha2:"",alpha3:"rom",bibliographic:"",name:"Romany"),
        Language(alpha2:"ro",alpha3:"ron",bibliographic:"rum",name:"Moldavian"),
        Language(alpha2:"ro",alpha3:"ron",bibliographic:"rum",name:"Romanian"),
        Language(alpha2:"rn",alpha3:"run",bibliographic:"",name:"Rundi"),
        Language(alpha2:"",alpha3:"rup",bibliographic:"",name:"Aromanian"),
        Language(alpha2:"",alpha3:"rup",bibliographic:"",name:"Arumanian"),
        Language(alpha2:"",alpha3:"rup",bibliographic:"",name:"Macedo-Romanian"),
        Language(alpha2:"ru",alpha3:"rus",bibliographic:"",name:"Russian"),
        Language(alpha2:"",alpha3:"sad",bibliographic:"",name:"Sandawe"),
        Language(alpha2:"sg",alpha3:"sag",bibliographic:"",name:"Sango"),
        Language(alpha2:"",alpha3:"sah",bibliographic:"",name:"Yakut"),
        Language(alpha2:"",alpha3:"sai",bibliographic:"",name:"South American Indian languages"),
        Language(alpha2:"",alpha3:"sal",bibliographic:"",name:"Salishan languages"),
        Language(alpha2:"",alpha3:"sam",bibliographic:"",name:"Samaritan Aramaic"),
        Language(alpha2:"sa",alpha3:"san",bibliographic:"",name:"Sanskrit"),
        Language(alpha2:"",alpha3:"sas",bibliographic:"",name:"Sasak"),
        Language(alpha2:"",alpha3:"sat",bibliographic:"",name:"Santali"),
        Language(alpha2:"",alpha3:"scn",bibliographic:"",name:"Sicilian"),
        Language(alpha2:"",alpha3:"sco",bibliographic:"",name:"Scots"),
        Language(alpha2:"",alpha3:"sel",bibliographic:"",name:"Selkup"),
        Language(alpha2:"",alpha3:"sem",bibliographic:"",name:"Semitic languages"),
        Language(alpha2:"",alpha3:"sga",bibliographic:"",name:"Irish, Old (to 900)"),
        Language(alpha2:"",alpha3:"sgn",bibliographic:"",name:"Sign Languages"),
        Language(alpha2:"",alpha3:"shn",bibliographic:"",name:"Shan"),
        Language(alpha2:"",alpha3:"sid",bibliographic:"",name:"Sidamo"),
        Language(alpha2:"si",alpha3:"sin",bibliographic:"",name:"Sinhala"),
        Language(alpha2:"si",alpha3:"sin",bibliographic:"",name:"Sinhalese"),
        Language(alpha2:"",alpha3:"sio",bibliographic:"",name:"Siouan languages"),
        Language(alpha2:"",alpha3:"sit",bibliographic:"",name:"Sino-Tibetan languages"),
        Language(alpha2:"",alpha3:"sla",bibliographic:"",name:"Slavic languages"),
        Language(alpha2:"sk",alpha3:"slk",bibliographic:"slo",name:"Slovak"),
        Language(alpha2:"sl",alpha3:"slv",bibliographic:"",name:"Slovenian"),
        Language(alpha2:"",alpha3:"sma",bibliographic:"",name:"Southern Sami"),
        Language(alpha2:"se",alpha3:"sme",bibliographic:"",name:"Northern Sami"),
        Language(alpha2:"",alpha3:"smi",bibliographic:"",name:"Sami languages"),
        Language(alpha2:"",alpha3:"smj",bibliographic:"",name:"Lule Sami"),
        Language(alpha2:"",alpha3:"smn",bibliographic:"",name:"Inari Sami"),
        Language(alpha2:"sm",alpha3:"smo",bibliographic:"",name:"Samoan"),
        Language(alpha2:"",alpha3:"sms",bibliographic:"",name:"Skolt Sami"),
        Language(alpha2:"sn",alpha3:"sna",bibliographic:"",name:"Shona"),
        Language(alpha2:"sd",alpha3:"snd",bibliographic:"",name:"Sindhi"),
        Language(alpha2:"",alpha3:"snk",bibliographic:"",name:"Soninke"),
        Language(alpha2:"",alpha3:"sog",bibliographic:"",name:"Sogdian"),
        Language(alpha2:"so",alpha3:"som",bibliographic:"",name:"Somali"),
        Language(alpha2:"",alpha3:"son",bibliographic:"",name:"Songhai languages"),
        Language(alpha2:"st",alpha3:"sot",bibliographic:"",name:"Sotho, Southern"),
        Language(alpha2:"es",alpha3:"spa",bibliographic:"",name:"Castilian"),
        Language(alpha2:"es",alpha3:"spa",bibliographic:"",name:"Spanish"),
        Language(alpha2:"sq",alpha3:"sqi",bibliographic:"alb",name:"Albanian"),
        Language(alpha2:"sc",alpha3:"srd",bibliographic:"",name:"Sardinian"),
        Language(alpha2:"",alpha3:"srn",bibliographic:"",name:"Sranan Tongo"),
        Language(alpha2:"sr",alpha3:"srp",bibliographic:"",name:"Serbian"),
        Language(alpha2:"",alpha3:"srr",bibliographic:"",name:"Serer"),
        Language(alpha2:"",alpha3:"ssa",bibliographic:"",name:"Nilo-Saharan languages"),
        Language(alpha2:"ss",alpha3:"ssw",bibliographic:"",name:"Swati"),
        Language(alpha2:"",alpha3:"suk",bibliographic:"",name:"Sukuma"),
        Language(alpha2:"su",alpha3:"sun",bibliographic:"",name:"Sundanese"),
        Language(alpha2:"",alpha3:"sus",bibliographic:"",name:"Susu"),
        Language(alpha2:"",alpha3:"sux",bibliographic:"",name:"Sumerian"),
        Language(alpha2:"sw",alpha3:"swa",bibliographic:"",name:"Swahili"),
        Language(alpha2:"sv",alpha3:"swe",bibliographic:"",name:"Swedish"),
        Language(alpha2:"",alpha3:"syc",bibliographic:"",name:"Classical Syriac"),
        Language(alpha2:"",alpha3:"syr",bibliographic:"",name:"Syriac"),
        Language(alpha2:"ty",alpha3:"tah",bibliographic:"",name:"Tahitian"),
        Language(alpha2:"",alpha3:"tai",bibliographic:"",name:"Tai languages"),
        Language(alpha2:"ta",alpha3:"tam",bibliographic:"",name:"Tamil"),
        Language(alpha2:"tt",alpha3:"tat",bibliographic:"",name:"Tatar"),
        Language(alpha2:"te",alpha3:"tel",bibliographic:"",name:"Telugu"),
        Language(alpha2:"",alpha3:"tem",bibliographic:"",name:"Timne"),
        Language(alpha2:"",alpha3:"ter",bibliographic:"",name:"Tereno"),
        Language(alpha2:"",alpha3:"tet",bibliographic:"",name:"Tetum"),
        Language(alpha2:"tg",alpha3:"tgk",bibliographic:"",name:"Tajik"),
        Language(alpha2:"tl",alpha3:"tgl",bibliographic:"",name:"Tagalog"),
        Language(alpha2:"th",alpha3:"tha",bibliographic:"",name:"Thai"),
        Language(alpha2:"",alpha3:"tig",bibliographic:"",name:"Tigre"),
        Language(alpha2:"ti",alpha3:"tir",bibliographic:"",name:"Tigrinya"),
        Language(alpha2:"",alpha3:"tiv",bibliographic:"",name:"Tiv"),
        Language(alpha2:"",alpha3:"tkl",bibliographic:"",name:"Tokelau"),
        Language(alpha2:"",alpha3:"tlh",bibliographic:"",name:"Klingon"),
        Language(alpha2:"",alpha3:"tlh",bibliographic:"",name:"tlhIngan-Hol"),
        Language(alpha2:"",alpha3:"tli",bibliographic:"",name:"Tlingit"),
        Language(alpha2:"",alpha3:"tmh",bibliographic:"",name:"Tamashek"),
        Language(alpha2:"",alpha3:"tog",bibliographic:"",name:"Tonga (Nyasa)"),
        Language(alpha2:"to",alpha3:"ton",bibliographic:"",name:"Tonga (Tonga Islands)"),
        Language(alpha2:"",alpha3:"tpi",bibliographic:"",name:"Tok Pisin"),
        Language(alpha2:"",alpha3:"tsi",bibliographic:"",name:"Tsimshian"),
        Language(alpha2:"tn",alpha3:"tsn",bibliographic:"",name:"Tswana"),
        Language(alpha2:"ts",alpha3:"tso",bibliographic:"",name:"Tsonga"),
        Language(alpha2:"tk",alpha3:"tuk",bibliographic:"",name:"Turkmen"),
        Language(alpha2:"",alpha3:"tum",bibliographic:"",name:"Tumbuka"),
        Language(alpha2:"",alpha3:"tup",bibliographic:"",name:"Tupi languages"),
        Language(alpha2:"tr",alpha3:"tur",bibliographic:"",name:"Turkish"),
        Language(alpha2:"",alpha3:"tut",bibliographic:"",name:"Altaic languages"),
        Language(alpha2:"",alpha3:"tvl",bibliographic:"",name:"Tuvalu"),
        Language(alpha2:"tw",alpha3:"twi",bibliographic:"",name:"Twi"),
        Language(alpha2:"",alpha3:"tyv",bibliographic:"",name:"Tuvinian"),
        Language(alpha2:"",alpha3:"udm",bibliographic:"",name:"Udmurt"),
        Language(alpha2:"",alpha3:"uga",bibliographic:"",name:"Ugaritic"),
        Language(alpha2:"ug",alpha3:"uig",bibliographic:"",name:"Uighur"),
        Language(alpha2:"ug",alpha3:"uig",bibliographic:"",name:"Uyghur"),
        Language(alpha2:"uk",alpha3:"ukr",bibliographic:"",name:"Ukrainian"),
        Language(alpha2:"",alpha3:"umb",bibliographic:"",name:"Umbundu"),
        Language(alpha2:"",alpha3:"und",bibliographic:"",name:"Undetermined"),
        Language(alpha2:"ur",alpha3:"urd",bibliographic:"",name:"Urdu"),
        Language(alpha2:"uz",alpha3:"uzb",bibliographic:"",name:"Uzbek"),
        Language(alpha2:"",alpha3:"vai",bibliographic:"",name:"Vai"),
        Language(alpha2:"ve",alpha3:"ven",bibliographic:"",name:"Venda"),
        Language(alpha2:"vi",alpha3:"vie",bibliographic:"",name:"Vietnamese"),
        Language(alpha2:"vo",alpha3:"vol",bibliographic:"",name:"Volapük"),
        Language(alpha2:"",alpha3:"vot",bibliographic:"",name:"Votic"),
        Language(alpha2:"",alpha3:"wak",bibliographic:"",name:"Wakashan languages"),
        Language(alpha2:"",alpha3:"wal",bibliographic:"",name:"Wolaitta"),
        Language(alpha2:"",alpha3:"wal",bibliographic:"",name:"Wolaytta"),
        Language(alpha2:"",alpha3:"war",bibliographic:"",name:"Waray"),
        Language(alpha2:"",alpha3:"was",bibliographic:"",name:"Washo"),
        Language(alpha2:"",alpha3:"wen",bibliographic:"",name:"Sorbian languages"),
        Language(alpha2:"wa",alpha3:"wln",bibliographic:"",name:"Walloon"),
        Language(alpha2:"wo",alpha3:"wol",bibliographic:"",name:"Wolof"),
        Language(alpha2:"",alpha3:"xal",bibliographic:"",name:"Kalmyk"),
        Language(alpha2:"",alpha3:"xal",bibliographic:"",name:"Oirat"),
        Language(alpha2:"xh",alpha3:"xho",bibliographic:"",name:"Xhosa"),
        Language(alpha2:"",alpha3:"yao",bibliographic:"",name:"Yao"),
        Language(alpha2:"",alpha3:"yap",bibliographic:"",name:"Yapese"),
        Language(alpha2:"yi",alpha3:"yid",bibliographic:"",name:"Yiddish"),
        Language(alpha2:"yo",alpha3:"yor",bibliographic:"",name:"Yoruba"),
        Language(alpha2:"",alpha3:"ypk",bibliographic:"",name:"Yupik languages"),
        Language(alpha2:"",alpha3:"zap",bibliographic:"",name:"Zapotec"),
        Language(alpha2:"",alpha3:"zbl",bibliographic:"",name:"Bliss"),
        Language(alpha2:"",alpha3:"zbl",bibliographic:"",name:"Blissymbolics"),
        Language(alpha2:"",alpha3:"zbl",bibliographic:"",name:"Blissymbols"),
        Language(alpha2:"",alpha3:"zen",bibliographic:"",name:"Zenaga"),
        Language(alpha2:"",alpha3:"zgh",bibliographic:"",name:"Standard Moroccan Tamazight"),
        Language(alpha2:"za",alpha3:"zha",bibliographic:"",name:"Chuang"),
        Language(alpha2:"za",alpha3:"zha",bibliographic:"",name:"Zhuang"),
        Language(alpha2:"zh",alpha3:"zho",bibliographic:"chi",name:"Chinese"),
        Language(alpha2:"",alpha3:"znd",bibliographic:"",name:"Zande languages"),
        Language(alpha2:"zu",alpha3:"zul",bibliographic:"",name:"Zulu"),
        Language(alpha2:"",alpha3:"zun",bibliographic:"",name:"Zuni"),
        Language(alpha2:"",alpha3:"zxx",bibliographic:"",name:"No linguistic content"),
        Language(alpha2:"",alpha3:"zxx",bibliographic:"",name:"Not applicable"),
        Language(alpha2:"",alpha3:"zza",bibliographic:"",name:"Dimili"),
        Language(alpha2:"",alpha3:"zza",bibliographic:"",name:"Dimli"),
        Language(alpha2:"",alpha3:"zza",bibliographic:"",name:"Kirdki"),
        Language(alpha2:"",alpha3:"zza",bibliographic:"",name:"Kirmanjki"),
        Language(alpha2:"",alpha3:"zza",bibliographic:"",name:"Zaza"),
        Language(alpha2:"",alpha3:"zza",bibliographic:"",name:"Zazaki")
    ]
}
