//
//  CurrencyISOModel.swift
//  BBChallenge
//
//  Created by Luis Alfonso Marquez Lecona on 2020-09-10.
//  Copyright © 2020 Busbud. All rights reserved.
//

import Foundation

/**
 Generic LanguageISOModel using  ISO 4217
 from vijinho ISO-Country-Data repository
*/
struct CurrencyISOModel: Codable, Identifiable {
    let id = UUID()
    let code: String
    let decimals: Int
    let name, number: String
}

typealias Currencies = [CurrencyISOModel]

// sample data set from vijinho ISO-Country-Data repository
extension CurrencyISOModel {
static let currencies: [CurrencyISOModel] = [
    CurrencyISOModel(code:"AED",decimals:2,name:"United Arab Emirates dirham",number:"784"),
    CurrencyISOModel(code:"AFN",decimals:2,name:"Afghan afghani",number:"971"),
    CurrencyISOModel(code:"ALL",decimals:2,name:"Albanian lek",number:"8"),
    CurrencyISOModel(code:"AMD",decimals:2,name:"Armenian dram",number:"51"),
    CurrencyISOModel(code:"ANG",decimals:2,name:"Netherlands Antillean guilder",number:"532"),
    CurrencyISOModel(code:"AOA",decimals:2,name:"Angolan kwanza",number:"973"),
    CurrencyISOModel(code:"ARS",decimals:2,name:"Argentine peso",number:"32"),
    CurrencyISOModel(code:"AUD",decimals:2,name:"Australian dollar",number:"36"),
    CurrencyISOModel(code:"AWG",decimals:2,name:"Aruban florin",number:"533"),
    CurrencyISOModel(code:"AZN",decimals:2,name:"Azerbaijani manat",number:"944"),
    CurrencyISOModel(code:"BAM",decimals:2,name:"Bosnia and Herzegovina convertible mark",number:"977"),
    CurrencyISOModel(code:"BBD",decimals:2,name:"Barbados dollar",number:"52"),
    CurrencyISOModel(code:"BDT",decimals:2,name:"Bangladeshi taka",number:"50"),
    CurrencyISOModel(code:"BGN",decimals:2,name:"Bulgarian lev",number:"975"),
    CurrencyISOModel(code:"BHD",decimals:3,name:"Bahraini dinar",number:"48"),
    CurrencyISOModel(code:"BIF",decimals:0,name:"Burundian franc",number:"108"),
    CurrencyISOModel(code:"BMD",decimals:2,name:"Bermudian dollar (customarily known as Bermuda dollar)",number:"60"),
    CurrencyISOModel(code:"BND",decimals:2,name:"Brunei dollar",number:"96"),
    CurrencyISOModel(code:"BOB",decimals:2,name:"Boliviano",number:"68"),
    CurrencyISOModel(code:"BOV",decimals:2,name:"Bolivian Mvdol (funds code)",number:"984"),
    CurrencyISOModel(code:"BRL",decimals:2,name:"Brazilian real",number:"986"),
    CurrencyISOModel(code:"BSD",decimals:2,name:"Bahamian dollar",number:"44"),
    CurrencyISOModel(code:"BTN",decimals:2,name:"Bhutanese ngultrum",number:"64"),
    CurrencyISOModel(code:"BWP",decimals:2,name:"Botswana pula",number:"72"),
    CurrencyISOModel(code:"BYR",decimals:0,name:"Belarusian ruble",number:"974"),
    CurrencyISOModel(code:"BZD",decimals:2,name:"Belize dollar",number:"84"),
    CurrencyISOModel(code:"CAD",decimals:2,name:"Canadian dollar",number:"124"),
    CurrencyISOModel(code:"CDF",decimals:2,name:"Congolese franc",number:"976"),
    CurrencyISOModel(code:"CHE",decimals:2,name:"WIR Euro (complementary currency)",number:"947"),
    CurrencyISOModel(code:"CHF",decimals:2,name:"Swiss franc",number:"756"),
    CurrencyISOModel(code:"CHW",decimals:2,name:"WIR Franc (complementary currency)",number:"948"),
    CurrencyISOModel(code:"CLF",decimals:0,name:"Unidad de Fomento (funds code)",number:"990"),
    CurrencyISOModel(code:"CLP",decimals:0,name:"Chilean peso",number:"152"),
    CurrencyISOModel(code:"CNY",decimals:2,name:"Chinese yuan",number:"156"),
    CurrencyISOModel(code:"COP",decimals:2,name:"Colombian peso",number:"170"),
    CurrencyISOModel(code:"COU",decimals:2,name:"Unidad de Valor Real",number:"970"),
    CurrencyISOModel(code:"CRC",decimals:2,name:"Costa Rican colon",number:"188"),
    CurrencyISOModel(code:"CUC",decimals:2,name:"Cuban convertible peso",number:"931"),
    CurrencyISOModel(code:"CUP",decimals:2,name:"Cuban peso",number:"192"),
    CurrencyISOModel(code:"CVE",decimals:0,name:"Cape Verde escudo",number:"132"),
    CurrencyISOModel(code:"CZK",decimals:2,name:"Czech koruna",number:"203"),
    CurrencyISOModel(code:"DJF",decimals:0,name:"Djiboutian franc",number:"262"),
    CurrencyISOModel(code:"DKK",decimals:2,name:"Danish krone",number:"208"),
    CurrencyISOModel(code:"DOP",decimals:2,name:"Dominican peso",number:"214"),
    CurrencyISOModel(code:"DZD",decimals:2,name:"Algerian dinar",number:"12"),
    CurrencyISOModel(code:"EGP",decimals:2,name:"Egyptian pound",number:"818"),
    CurrencyISOModel(code:"ERN",decimals:2,name:"Eritrean nakfa",number:"232"),
    CurrencyISOModel(code:"ETB",decimals:2,name:"Ethiopian birr",number:"230"),
    CurrencyISOModel(code:"EUR",decimals:2,name:"Euro",number:"978"),
    CurrencyISOModel(code:"FJD",decimals:2,name:"Fiji dollar",number:"242"),
    CurrencyISOModel(code:"FKP",decimals:2,name:"Falkland Islands pound",number:"238"),
    CurrencyISOModel(code:"GBP",decimals:2,name:"Pound sterling",number:"826"),
    CurrencyISOModel(code:"GEL",decimals:2,name:"Georgian lari",number:"981"),
    CurrencyISOModel(code:"GHS",decimals:2,name:"Ghanaian cedi",number:"936"),
    CurrencyISOModel(code:"GIP",decimals:2,name:"Gibraltar pound",number:"292"),
    CurrencyISOModel(code:"GMD",decimals:2,name:"Gambian dalasi",number:"270"),
    CurrencyISOModel(code:"GNF",decimals:0,name:"Guinean franc",number:"324"),
    CurrencyISOModel(code:"GTQ",decimals:2,name:"Guatemalan quetzal",number:"320"),
    CurrencyISOModel(code:"GYD",decimals:2,name:"Guyanese dollar",number:"328"),
    CurrencyISOModel(code:"HKD",decimals:2,name:"Hong Kong dollar",number:"344"),
    CurrencyISOModel(code:"HNL",decimals:2,name:"Honduran lempira",number:"340"),
    CurrencyISOModel(code:"HRK",decimals:2,name:"Croatian kuna",number:"191"),
    CurrencyISOModel(code:"HTG",decimals:2,name:"Haitian gourde",number:"332"),
    CurrencyISOModel(code:"HUF",decimals:2,name:"Hungarian forint",number:"348"),
    CurrencyISOModel(code:"IDR",decimals:2,name:"Indonesian rupiah",number:"360"),
    CurrencyISOModel(code:"ILS",decimals:2,name:"Israeli new shekel",number:"376"),
    CurrencyISOModel(code:"INR",decimals:2,name:"Indian rupee",number:"356"),
    CurrencyISOModel(code:"IQD",decimals:3,name:"Iraqi dinar",number:"368"),
    CurrencyISOModel(code:"IRR",decimals:0,name:"Iranian rial",number:"364"),
    CurrencyISOModel(code:"ISK",decimals:0,name:"Icelandic króna",number:"352"),
    CurrencyISOModel(code:"JMD",decimals:2,name:"Jamaican dollar",number:"388"),
    CurrencyISOModel(code:"JOD",decimals:3,name:"Jordanian dinar",number:"400"),
    CurrencyISOModel(code:"JPY",decimals:0,name:"Japanese yen",number:"392"),
    CurrencyISOModel(code:"KES",decimals:2,name:"Kenyan shilling",number:"404"),
    CurrencyISOModel(code:"KGS",decimals:2,name:"Kyrgyzstani som",number:"417"),
    CurrencyISOModel(code:"KHR",decimals:2,name:"Cambodian riel",number:"116"),
    CurrencyISOModel(code:"KMF",decimals:0,name:"Comoro franc",number:"174"),
    CurrencyISOModel(code:"KPW",decimals:0,name:"North Korean won",number:"408"),
    CurrencyISOModel(code:"KRW",decimals:0,name:"South Korean won",number:"410"),
    CurrencyISOModel(code:"KWD",decimals:3,name:"Kuwaiti dinar",number:"414"),
    CurrencyISOModel(code:"KYD",decimals:2,name:"Cayman Islands dollar",number:"136"),
    CurrencyISOModel(code:"KZT",decimals:2,name:"Kazakhstani tenge",number:"398"),
    CurrencyISOModel(code:"LAK",decimals:0,name:"Lao kip",number:"418"),
    CurrencyISOModel(code:"LBP",decimals:0,name:"Lebanese pound",number:"422"),
    CurrencyISOModel(code:"LKR",decimals:2,name:"Sri Lankan rupee",number:"144"),
    CurrencyISOModel(code:"LRD",decimals:2,name:"Liberian dollar",number:"430"),
    CurrencyISOModel(code:"LSL",decimals:2,name:"Lesotho loti",number:"426"),
    CurrencyISOModel(code:"LTL",decimals:2,name:"Lithuanian litas",number:"440"),
    CurrencyISOModel(code:"LVL",decimals:2,name:"Latvian lats",number:"428"),
    CurrencyISOModel(code:"LYD",decimals:3,name:"Libyan dinar",number:"434"),
    CurrencyISOModel(code:"MAD",decimals:2,name:"Moroccan dirham",number:"504"),
    CurrencyISOModel(code:"MDL",decimals:2,name:"Moldovan leu",number:"498"),
    CurrencyISOModel(code:"MGA",decimals:0,name:"Malagasy ariary",number:"969"),
    CurrencyISOModel(code:"MKD",decimals:0,name:"Macedonian denar",number:"807"),
    CurrencyISOModel(code:"MMK",decimals:0,name:"Myanma kyat",number:"104"),
    CurrencyISOModel(code:"MNT",decimals:2,name:"Mongolian tugrik",number:"496"),
    CurrencyISOModel(code:"MOP",decimals:2,name:"Macanese pataca",number:"446"),
    CurrencyISOModel(code:"MRO",decimals:0,name:"Mauritanian ouguiya",number:"478"),
    CurrencyISOModel(code:"MUR",decimals:2,name:"Mauritian rupee",number:"480"),
    CurrencyISOModel(code:"MVR",decimals:2,name:"Maldivian rufiyaa",number:"462"),
    CurrencyISOModel(code:"MWK",decimals:2,name:"Malawian kwacha",number:"454"),
    CurrencyISOModel(code:"MXN",decimals:2,name:"Mexican peso",number:"484"),
    CurrencyISOModel(code:"MXV",decimals:2,name:"Mexican Unidad de Inversion (UDI) (funds code)",number:"979"),
    CurrencyISOModel(code:"MYR",decimals:2,name:"Malaysian ringgit",number:"458"),
    CurrencyISOModel(code:"MZN",decimals:2,name:"Mozambican metical",number:"943"),
    CurrencyISOModel(code:"NAD",decimals:2,name:"Namibian dollar",number:"516"),
    CurrencyISOModel(code:"NGN",decimals:2,name:"Nigerian naira",number:"566"),
    CurrencyISOModel(code:"NIO",decimals:2,name:"Nicaraguan córdoba",number:"558"),
    CurrencyISOModel(code:"NOK",decimals:2,name:"Norwegian krone",number:"578"),
    CurrencyISOModel(code:"NPR",decimals:2,name:"Nepalese rupee",number:"524"),
    CurrencyISOModel(code:"NZD",decimals:2,name:"New Zealand dollar",number:"554"),
    CurrencyISOModel(code:"OMR",decimals:3,name:"Omani rial",number:"512"),
    CurrencyISOModel(code:"PAB",decimals:2,name:"Panamanian balboa",number:"590"),
    CurrencyISOModel(code:"PEN",decimals:2,name:"Peruvian nuevo sol",number:"604"),
    CurrencyISOModel(code:"PGK",decimals:2,name:"Papua New Guinean kina",number:"598"),
    CurrencyISOModel(code:"PHP",decimals:2,name:"Philippine peso",number:"608"),
    CurrencyISOModel(code:"PKR",decimals:2,name:"Pakistani rupee",number:"586"),
    CurrencyISOModel(code:"PLN",decimals:2,name:"Polish złoty",number:"985"),
    CurrencyISOModel(code:"PYG",decimals:0,name:"Paraguayan guaraní",number:"600"),
    CurrencyISOModel(code:"QAR",decimals:2,name:"Qatari riyal",number:"634"),
    CurrencyISOModel(code:"RON",decimals:2,name:"Romanian new leu",number:"946"),
    CurrencyISOModel(code:"RSD",decimals:2,name:"Serbian dinar",number:"941"),
    CurrencyISOModel(code:"RUB",decimals:2,name:"Russian rouble",number:"643"),
    CurrencyISOModel(code:"RWF",decimals:0,name:"Rwandan franc",number:"646"),
    CurrencyISOModel(code:"SAR",decimals:2,name:"Saudi riyal",number:"682"),
    CurrencyISOModel(code:"SBD",decimals:2,name:"Solomon Islands dollar",number:"90"),
    CurrencyISOModel(code:"SCR",decimals:2,name:"Seychelles rupee",number:"690"),
    CurrencyISOModel(code:"SDG",decimals:2,name:"Sudanese pound",number:"938"),
    CurrencyISOModel(code:"SEK",decimals:2,name:"Swedish krona/kronor",number:"752"),
    CurrencyISOModel(code:"SGD",decimals:2,name:"Singapore dollar",number:"702"),
    CurrencyISOModel(code:"SHP",decimals:2,name:"Saint Helena pound",number:"654"),
    CurrencyISOModel(code:"SLL",decimals:0,name:"Sierra Leonean leone",number:"694"),
    CurrencyISOModel(code:"SOS",decimals:2,name:"Somali shilling",number:"706"),
    CurrencyISOModel(code:"SRD",decimals:2,name:"Surinamese dollar",number:"968"),
    CurrencyISOModel(code:"SSP",decimals:2,name:"South Sudanese pound",number:"728"),
    CurrencyISOModel(code:"STD",decimals:0,name:"São Tomé and Príncipe dobra",number:"678"),
    CurrencyISOModel(code:"SYP",decimals:2,name:"Syrian pound",number:"760"),
    CurrencyISOModel(code:"SZL",decimals:2,name:"Swazi lilangeni",number:"748"),
    CurrencyISOModel(code:"THB",decimals:2,name:"Thai baht",number:"764"),
    CurrencyISOModel(code:"TJS",decimals:2,name:"Tajikistani somoni",number:"972"),
    CurrencyISOModel(code:"TMT",decimals:2,name:"Turkmenistani manat",number:"934"),
    CurrencyISOModel(code:"TND",decimals:3,name:"Tunisian dinar",number:"788"),
    CurrencyISOModel(code:"TOP",decimals:2,name:"Tongan paʻanga",number:"776"),
    CurrencyISOModel(code:"TRY",decimals:2,name:"Turkish lira",number:"949"),
    CurrencyISOModel(code:"TTD",decimals:2,name:"Trinidad and Tobago dollar",number:"780"),
    CurrencyISOModel(code:"TWD",decimals:2,name:"New Taiwan dollar",number:"901"),
    CurrencyISOModel(code:"TZS",decimals:2,name:"Tanzanian shilling",number:"834"),
    CurrencyISOModel(code:"UAH",decimals:2,name:"Ukrainian hryvnia",number:"980"),
    CurrencyISOModel(code:"UGX",decimals:2,name:"Ugandan shilling",number:"800"),
    CurrencyISOModel(code:"USD",decimals:2,name:"United States dollar",number:"840"),
    CurrencyISOModel(code:"USN",decimals:2,name:"United States dollar (next day) (funds code)",number:"997"),
    CurrencyISOModel(code:"USS",decimals:2,name:"United States dollar (same day) (funds code) (one source[who?] claims it is no longer used, but it is still on the ISO 4217-MA list)",number:"998"),
    CurrencyISOModel(code:"UYI",decimals:0,name:"Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)",number:"940"),
    CurrencyISOModel(code:"UYU",decimals:2,name:"Uruguayan peso",number:"858"),
    CurrencyISOModel(code:"UZS",decimals:2,name:"Uzbekistan som",number:"860"),
    CurrencyISOModel(code:"VEF",decimals:2,name:"Venezuelan bolívar fuerte",number:"937"),
    CurrencyISOModel(code:"VND",decimals:0,name:"Vietnamese dong",number:"704"),
    CurrencyISOModel(code:"VUV",decimals:0,name:"Vanuatu vatu",number:"548"),
    CurrencyISOModel(code:"WST",decimals:2,name:"Samoan tala",number:"882"),
    CurrencyISOModel(code:"XAF",decimals:0,name:"CFA franc BEAC",number:"950"),
    CurrencyISOModel(code:"XAG",decimals:0,name:"Silver (one troy ounce)",number:"961"),
    CurrencyISOModel(code:"XAU",decimals:0,name:"Gold (one troy ounce)",number:"959"),
    CurrencyISOModel(code:"XBA",decimals:0,name:"European Composite Unit (EURCO) (bond market unit)",number:"955"),
    CurrencyISOModel(code:"XBB",decimals:0,name:"European Monetary Unit (E.M.U.-6) (bond market unit)",number:"956"),
    CurrencyISOModel(code:"XBC",decimals:0,name:"European Unit of Account 9 (E.U.A.-9) (bond market unit)",number:"957"),
    CurrencyISOModel(code:"XBD",decimals:0,name:"European Unit of Account 17 (E.U.A.-17) (bond market unit)",number:"958"),
    CurrencyISOModel(code:"XCD",decimals:2,name:"East Caribbean dollar",number:"951"),
    CurrencyISOModel(code:"XDR",decimals:0,name:"Special drawing rights",number:"960"),
    CurrencyISOModel(code:"XFU",decimals:0,name:"UIC franc (special settlement currency)",number:"Nil"),
    CurrencyISOModel(code:"XOF",decimals:0,name:"CFA franc BCEAO",number:"952"),
    CurrencyISOModel(code:"XPD",decimals:0,name:"Palladium (one troy ounce)",number:"964"),
    CurrencyISOModel(code:"XPF",decimals:0,name:"CFP franc",number:"953"),
    CurrencyISOModel(code:"XPT",decimals:0,name:"Platinum (one troy ounce)",number:"962"),
    CurrencyISOModel(code:"XTS",decimals:0,name:"Code reserved for testing purposes",number:"963"),
    CurrencyISOModel(code:"XXX",decimals:0,name:"No currency",number:"999"),
    CurrencyISOModel(code:"YER",decimals:2,name:"Yemeni rial",number:"886"),
    CurrencyISOModel(code:"ZAR",decimals:2,name:"South African rand",number:"710"),
    CurrencyISOModel(code:"ZMW",decimals:2,name:"Zambian kwacha",number:"967")
]
}
