//
//  HomeViewController.swift
//  Osheaga Routes
//
//  Created by user on 01/11/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class HomeViewController: UIViewController {

    // MARK: - Public properties -

    @IBOutlet weak var messageView: UIView!
    @IBOutlet weak var messageLabel: UILabel!
    
    @IBOutlet weak var tryAgainButton: UIButton!
    
    @IBOutlet weak var resultsTableView: UITableView!
    @IBOutlet var searchResultsDataSource: SearchResultsTableViewDataSource!
    
    var presenter: HomePresenterInterface! {
        didSet {
            searchResultsDataSource.delegate = presenter as? SearchResultsTableViewDataSourceDelegate
        }
    }

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.viewDidLoad()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        setUpNavigationBar()
    }

    private func setUpNavigationBar() {
        
        // Making sure the navigation bar goes perfect with the search box
        
        title = "Bus Tickets"
        
        navigationController?.navigationBar.barStyle = .black
        navigationController?.navigationBar.isTranslucent = false
        navigationController?.navigationBar.setBackgroundImage(UIImage(), for: .default)
        navigationController?.navigationBar.shadowImage = UIImage()
        
        if #available(iOS 13.0, *) {
            navigationController?.navigationBar.scrollEdgeAppearance?.shadowColor = .clear
        }
        
        if #available(iOS 11.0, *) {
            navigationController?.navigationBar.barTintColor = UIColor(named: "SecondaryColor")
        } else {
            navigationController?.navigationBar.barTintColor = UIColor(hex: "#127CCB")
        }
        
        navigationController?.navigationBar.titleTextAttributes = [.foregroundColor: UIColor.white]

    }
    
    override func traitCollectionDidChange(_ previousTraitCollection: UITraitCollection?) {
        super.traitCollectionDidChange(previousTraitCollection)
        if #available(iOS 13.0, *) {
            // Seems overkill but I found a pesky little bug regarding dark/light mode changing
            // in certain situations it wouldn't automatically change its color even if I did
            // set it (implicity).
            navigationController?.navigationBar.barTintColor = UIColor(named: "SecondaryColor")?.resolvedColor(with: .current)
        }
    }
    
    @IBAction func didPressSearch(_ sender: Any) {
        presenter.onUserPressedSearch()
    }
}

// MARK: - Extensions -

extension HomeViewController: HomeViewInterface {
    
    func reloadResultsTableView() {
        DispatchQueue.main.async {
            self.resultsTableView.reloadData()
        }
    }
 
    func setMessage(_ message: String?, tryAgainButtonHidden: Bool) {
        
        DispatchQueue.main.async {
            UIView.animate(withDuration: 0.3) {
                self.messageView.isHidden = message == nil
                self.messageLabel.text = message
                self.tryAgainButton.isHidden = tryAgainButtonHidden
            }
        }
        
    }
}
