//
//  HomeInteractor.swift
//  Osheaga Routes
//
//  Created by user on 01/11/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class HomeInteractor {
    var searchResult: SearchResult?
}

// MARK: - Extensions -

extension HomeInteractor: HomeInteractorInterface {
    
    func getSearchResultsCount() -> Int {
        return searchResult?.departures?.count ?? 0
    }
    
    func getSearchResultsDeparture(at indexPath: IndexPath) -> Departure? {
        guard (searchResult?.departures?.count ?? 0) > indexPath.row else { return nil }
        return searchResult?.departures?[indexPath.row]
        
    }
    
    func getSearchResultsLocation(with id: Int) -> Location? {
        
        return (searchResult?.locations ?? []).first { (location) -> Bool in
            return location.id == id
        }
        
    }
    
    
    func performSearch(searchParams: SearchParameters, completion: @escaping (_ success: Bool, _ error: Error?) -> Void) {
        
        let from = searchParams.fromCity
        let to = searchParams.toCity
        
        let date = searchParams.date
        let adultsCount = searchParams.adultsCount
        
        NetworkLayer.shared.getRoutes(from: from, to: to, at: date, for: adultsCount) { (result, error) in
            
            guard error == nil else {
                completion(false, error)
                return
            }
            
            DispatchQueue.main.async {
                self.searchResult = result
                completion(true, nil)
            }
        }
    }
}
