# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BusbudOsheaga' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BusbudOsheaga

    pod 'PromiseKit'
    pod 'PromiseKit/Alamofire'
    pod 'SDWebImage'

  target 'BusbudOsheagaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
