//
//  OnboardingPresenter.swift
//  Osheaga Routes
//
//  Created by user on 01/11/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class OnboardingPresenter {

    // MARK: - Private properties -

    private unowned let view: OnboardingViewInterface
    private let interactor: OnboardingInteractorInterface
    private let wireframe: OnboardingWireframeInterface

    private var nextButtonIsExpanded = false
    
    // MARK: - Lifecycle -

    init(view: OnboardingViewInterface, interactor: OnboardingInteractorInterface, wireframe: OnboardingWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension OnboardingPresenter: OnboardingPresenterInterface {
    
    func userDidPressProceed() {
        
        if nextButtonIsExpanded {
            wireframe.dismiss()
        }else{
            view.scrollToNextOnboardingStep()
        }
        
    }
 
}


extension OnboardingPresenter: OnboardingCollectionViewDelegate {
    
    func getOnboardingTitle(at index: Int) -> String {
        let onboardingStep = interactor.getOnboardingStep(at: index)
        return onboardingStep?.title ?? ""
    }
    
    func getOnboardingBody(at index: Int) -> String {
        let onboardingStep = interactor.getOnboardingStep(at: index)
        return onboardingStep?.body ?? ""        
    }
    
    
    func getOnboardingAnimation(at index: Int) -> Any? {
        let onboardingStep = interactor.getOnboardingStep(at: index)
        return onboardingStep?.animation ?? ""
    }
    
    func userArrivedOnEnd() {
        nextButtonIsExpanded = true
        view.setNextButton(expandedMode: nextButtonIsExpanded)
    }
    
    func userLeavingEnd() {
        nextButtonIsExpanded = false
        view.setNextButton(expandedMode: nextButtonIsExpanded)
    }
}
