//
//  OnboardingViewController.swift
//  Osheaga Routes
//
//  Created by user on 01/11/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class OnboardingViewController: UIViewController {
    
    
    // MARK: - Public properties -
    
    @IBOutlet weak var nextButton: GradientButton!
    @IBOutlet weak var onboardingCollectionView: UICollectionView!
    
    @IBOutlet var aspectRatioNextButtonConstraint: NSLayoutConstraint!
    
    @IBOutlet var dataSource: OnboardingCollectionViewDataSource!
    @IBOutlet var backgroundShapes: [UIView]! {
        didSet {
            guard backgroundShapes.count >= 2 else { return }
            backgroundShapes[0].rotate(byAngle: -20, ofType: .degrees)
            backgroundShapes[1].rotate(byAngle: 10, ofType: .degrees)
        }
    }
    
    var presenter: OnboardingPresenterInterface!{
        didSet {
            guard presenter != nil && dataSource != nil else { return }
            dataSource.delegate = self.presenter as? OnboardingCollectionViewDelegate
        }
    }

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }

    @IBAction func didPressProceed(_ sender: Any) {
        presenter.userDidPressProceed()
    }
}

// MARK: - Extensions -

extension OnboardingViewController: OnboardingViewInterface {
    
    func setNextButton(expandedMode: Bool) {
        
        self.nextButton.setImage(UIImage(), for: .normal)
        self.nextButton.setTitle("", for: .normal)
        
        let animationOptions: UIView.AnimationOptions = [.beginFromCurrentState,
                                                         .preferredFramesPerSecond60,
                                                         .curveEaseInOut]
        
        
        UIView.animate(withDuration: 0.3, delay: 0, options: animationOptions) {
            
            self.aspectRatioNextButtonConstraint.isActive = !expandedMode
            self.view.layoutIfNeeded()
            
        } completion: { (_) in
            
            let image = expandedMode ? nil : UIImage.init(named: "ic-next-arrow")
            let title = expandedMode ? "LET'S GO" : nil
            
            self.nextButton.setImage(image, for: .normal)
            self.nextButton.setTitle(title, for: .normal)
            
        }

    }
    
    func scrollToNextOnboardingStep() {
        dataSource.scrollToNextOnboardingStep(in: onboardingCollectionView)
    }
}
