//
//  OnboardingInterfaces.swift
//  Osheaga Routes
//
//  Created by user on 01/11/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

struct OnboardingStep {
    let title, body: String
    let animation: Any
}

protocol OnboardingWireframeInterface: WireframeInterface {
    func dismiss()
}

protocol OnboardingViewInterface: ViewInterface {
    func setNextButton(expandedMode: Bool)
    func scrollToNextOnboardingStep()
}

protocol OnboardingPresenterInterface: PresenterInterface {
    func userDidPressProceed()
}

protocol OnboardingInteractorInterface: InteractorInterface {
    func getOnboardingStep(at index: Int) -> OnboardingStep?
    func getStepsCount() -> Int
}
